package com.egakh.familytree.permissions;

import com.egakh.familytree.data.AnimalRecord;
import java.util.UUID;

/** Public tree viewing never grants location or editing access. */
public final class PetAccess {
    private PetAccess() {}

    public static boolean canView(AnimalRecord pet, UUID player, boolean viewAll) {
        return pet != null && (viewAll || owns(pet, player));
    }

    public static boolean canManage(AnimalRecord pet, UUID player, boolean operator) {
        return pet != null && (operator || owns(pet, player));
    }

    private static boolean owns(AnimalRecord pet, UUID player) {
        return player != null && player.equals(pet.ownerId());
    }

    public static AnimalRecord forViewer(AnimalRecord pet, UUID player, boolean operator) {
        AnimalRecord publicPet = new AnimalRecord(pet.id(), pet.speciesId(), pet.originalName(), pet.nameAutogenerated(),
                pet.parentA(), pet.parentB(), pet.birthWorldDay(), pet.birthEpochMillis(), pet.deceased(),
                pet.deathWorldDay(), pet.deathEpochMillis(), pet.ownerId(), pet.ownerName(), pet.variantId(),
                canManage(pet, player, operator) ? pet.lastSeen() : null, pet.deathCause());
        publicPet.setTreeName(pet.treeName());
        return publicPet;
    }
}
