package com.egakh.familytree.naming;

import com.egakh.familytree.data.AnimalRecord;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class PetRenamingTest {
    private final UUID owner = UUID.randomUUID();
    private final AnimalRecord record = new AnimalRecord(UUID.randomUUID(), "minecraft:wolf", "Wolf", true,
            null, null, 7, 1234, false, null, null, owner, "Owner", null, null, null);

    @Test
    void ownerChangesOnlyTheTreeName() {
        assertEquals(PetRenaming.Result.SUCCESS, PetRenaming.rename(record, owner, false, "  Snowball  "));
        assertEquals("Snowball", record.name());
        assertEquals("Wolf", record.originalName());
        assertTrue(record.nameAutogenerated());
        assertEquals(7, record.birthWorldDay());
        assertTrue(record.matchesName("snowball"));
        assertTrue(record.matchesName("wolf"));
        assertFalse(record.matchesName("another pet"));
    }

    @Test
    void entityNameChangesKeepTheTreeNameUntilItIsReset() {
        PetRenaming.rename(record, owner, false, "Snowball");
        record.rename("Rover", false);
        assertEquals("Snowball", record.name());
        assertEquals(PetRenaming.Result.SUCCESS, PetRenaming.rename(record, owner, false, ""));
        assertNull(record.treeName());
        assertEquals("Rover", record.name());
        assertFalse(record.nameAutogenerated());
    }

    @Test
    void rejectsAnotherPlayerEvenWhenTheyCanViewThePet() {
        record.setTreeName("Snowball");
        assertEquals(PetRenaming.Result.NOT_ALLOWED, PetRenaming.rename(record, UUID.randomUUID(), false, "Other"));
        assertEquals(PetRenaming.Result.NOT_ALLOWED, PetRenaming.rename(record, UUID.randomUUID(), false, ""));
        assertEquals("Snowball", record.name());
    }

    @Test
    void allowsOperatorsAndDeceasedRecords() {
        record.markDeceased(15, 5678, null);
        assertEquals(PetRenaming.Result.SUCCESS, PetRenaming.rename(record, UUID.randomUUID(), true, "Old friend"));
        assertTrue(record.deceased());
        assertEquals(15, record.deathWorldDay());
        assertEquals("Wolf", record.originalName());
    }

    @Test
    void validatesNamesOnTheServerWithoutChangingTheExistingName() {
        for (String invalid : new String[]{" ", "\t", "x\ny", "x\u00a7ay", "x\u007fy", "x\u0085y", "\ud800", "x".repeat(65)}) {
            assertEquals(PetRenaming.Result.INVALID_NAME, PetRenaming.rename(record, owner, false, invalid));
            assertNull(record.treeName());
        }
        assertEquals(PetRenaming.Result.INVALID_NAME, PetRenaming.rename(record, owner, false, null));
        assertTrue(PetRenaming.isValidName("x".repeat(64)));
        assertTrue(PetRenaming.isValidName("\u0421\u043d\u0435\u0436\u043e\u043a \ud83d\udc3a"));
    }

    @Test
    void rejectsMissingOrUnownedPetsForOrdinaryPlayers() {
        assertEquals(PetRenaming.Result.NOT_FOUND, PetRenaming.rename(null, owner, true, "Name"));
        record.setOwner(null, null);
        assertEquals(PetRenaming.Result.NOT_ALLOWED, PetRenaming.rename(record, owner, false, "Name"));
        assertEquals(PetRenaming.Result.SUCCESS, PetRenaming.rename(record, owner, true, "Name"));
    }
}
