package com.egakh.familytree.data;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.UUIDUtil;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;

import java.util.Optional;
import java.util.UUID;

public final class AnimalRecord {
    private final UUID id;
    private String speciesId;
    private String name;
    private boolean nameAutogenerated;
    private UUID parentA;
    private UUID parentB;
    private final long birthWorldDay;
    private final long birthEpochMillis;
    private boolean deceased;
    private Long deathWorldDay;
    private Long deathEpochMillis;
    private UUID ownerId;

    public AnimalRecord(UUID id, String speciesId, String name, boolean nameAutogenerated,
                        UUID parentA, UUID parentB,
                        long birthWorldDay, long birthEpochMillis,
                        boolean deceased, Long deathWorldDay, Long deathEpochMillis,
                        UUID ownerId) {
        this.id = id;
        this.speciesId = speciesId;
        this.name = name;
        this.nameAutogenerated = nameAutogenerated;
        this.parentA = parentA;
        this.parentB = parentB;
        this.birthWorldDay = birthWorldDay;
        this.birthEpochMillis = birthEpochMillis;
        this.deceased = deceased;
        this.deathWorldDay = deathWorldDay;
        this.deathEpochMillis = deathEpochMillis;
        this.ownerId = ownerId;
    }

    public UUID id() { return id; }
    public String speciesId() { return speciesId; }
    public String name() { return name; }
    public boolean nameAutogenerated() { return nameAutogenerated; }
    public UUID parentA() { return parentA; }
    public UUID parentB() { return parentB; }
    public long birthWorldDay() { return birthWorldDay; }
    public long birthEpochMillis() { return birthEpochMillis; }
    public boolean deceased() { return deceased; }
    public Long deathWorldDay() { return deathWorldDay; }
    public Long deathEpochMillis() { return deathEpochMillis; }
    public UUID ownerId() { return ownerId; }

    public void rename(String newName, boolean fromAutoGenerator) {
        this.name = newName;
        this.nameAutogenerated = fromAutoGenerator;
    }

    public void markDeceased(long worldDay, long epochMillis) {
        this.deceased = true;
        this.deathWorldDay = worldDay;
        this.deathEpochMillis = epochMillis;
    }

    public void setOwner(UUID ownerId) {
        this.ownerId = ownerId;
    }

    public void setSpeciesId(String speciesId) {
        this.speciesId = speciesId;
    }

    public static final Codec<AnimalRecord> CODEC = RecordCodecBuilder.create(instance -> instance.group(
            UUIDUtil.CODEC.fieldOf("id").forGetter(AnimalRecord::id),
            Codec.STRING.fieldOf("species").forGetter(AnimalRecord::speciesId),
            Codec.STRING.fieldOf("name").forGetter(AnimalRecord::name),
            Codec.BOOL.optionalFieldOf("name_auto", false).forGetter(AnimalRecord::nameAutogenerated),
            UUIDUtil.CODEC.optionalFieldOf("parent_a").forGetter(r -> Optional.ofNullable(r.parentA)),
            UUIDUtil.CODEC.optionalFieldOf("parent_b").forGetter(r -> Optional.ofNullable(r.parentB)),
            Codec.LONG.fieldOf("birth_world_day").forGetter(AnimalRecord::birthWorldDay),
            Codec.LONG.fieldOf("birth_epoch").forGetter(AnimalRecord::birthEpochMillis),
            Codec.BOOL.optionalFieldOf("deceased", false).forGetter(AnimalRecord::deceased),
            Codec.LONG.optionalFieldOf("death_world_day").forGetter(r -> Optional.ofNullable(r.deathWorldDay)),
            Codec.LONG.optionalFieldOf("death_epoch").forGetter(r -> Optional.ofNullable(r.deathEpochMillis)),
            UUIDUtil.CODEC.optionalFieldOf("owner").forGetter(r -> Optional.ofNullable(r.ownerId))
    ).apply(instance, (id, species, name, nameAuto, pa, pb, bd, be, dec, dwd, dem, owner) ->
            new AnimalRecord(id, species, name, nameAuto,
                    pa.orElse(null), pb.orElse(null),
                    bd, be,
                    dec, dwd.orElse(null), dem.orElse(null),
                    owner.orElse(null))));

    public static final StreamCodec<FriendlyByteBuf, AnimalRecord> STREAM_CODEC = StreamCodec.composite(
            UUIDUtil.STREAM_CODEC,
            AnimalRecord::id,
            ByteBufCodecs.STRING_UTF8,
            AnimalRecord::speciesId,
            ByteBufCodecs.STRING_UTF8,
            AnimalRecord::name,
            ByteBufCodecs.BOOL,
            AnimalRecord::nameAutogenerated,
            ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC),
            r -> Optional.ofNullable(r.parentA),
            ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC),
            r -> Optional.ofNullable(r.parentB),
            ByteBufCodecs.LONG,
            AnimalRecord::birthWorldDay,
            ByteBufCodecs.LONG,
            AnimalRecord::birthEpochMillis,
            ByteBufCodecs.BOOL,
            AnimalRecord::deceased,
            ByteBufCodecs.optional(ByteBufCodecs.LONG),
            r -> Optional.ofNullable(r.deathWorldDay),
            ByteBufCodecs.optional(ByteBufCodecs.LONG),
            r -> Optional.ofNullable(r.deathEpochMillis),
            ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC),
            r -> Optional.ofNullable(r.ownerId),
            (id, species, name, nameAuto, parentA, parentB, birthWorldDay, birthEpochMillis, deceased,
             deathWorldDay, deathEpochMillis, ownerId) ->
                    new AnimalRecord(id, species, name, nameAuto,
                            parentA.orElse(null), parentB.orElse(null),
                            birthWorldDay, birthEpochMillis,
                            deceased, deathWorldDay.orElse(null), deathEpochMillis.orElse(null),
                            ownerId.orElse(null))
    );
}
