package com.egakh.familytree.data;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.UUIDUtil;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;

import java.util.Optional;
import java.util.UUID;

public final class AnimalRecord {

    public record LastSeen(double x, double y, double z, String dimension, long worldDay) {
        public static final Codec<LastSeen> CODEC = RecordCodecBuilder.create(instance -> instance.group(
                Codec.DOUBLE.fieldOf("x").forGetter(LastSeen::x),
                Codec.DOUBLE.fieldOf("y").forGetter(LastSeen::y),
                Codec.DOUBLE.fieldOf("z").forGetter(LastSeen::z),
                Codec.STRING.fieldOf("dimension").forGetter(LastSeen::dimension),
                Codec.LONG.fieldOf("world_day").forGetter(LastSeen::worldDay)
        ).apply(instance, LastSeen::new));

        public static final StreamCodec<FriendlyByteBuf, LastSeen> STREAM_CODEC = StreamCodec.composite(
                ByteBufCodecs.DOUBLE, LastSeen::x,
                ByteBufCodecs.DOUBLE, LastSeen::y,
                ByteBufCodecs.DOUBLE, LastSeen::z,
                ByteBufCodecs.STRING_UTF8, LastSeen::dimension,
                ByteBufCodecs.LONG, LastSeen::worldDay,
                LastSeen::new);
    }

    public record DeathCause(String attacker, String msgId) {
        public static final Codec<DeathCause> CODEC = RecordCodecBuilder.create(instance -> instance.group(
                Codec.STRING.optionalFieldOf("attacker").forGetter(c -> Optional.ofNullable(c.attacker)),
                Codec.STRING.optionalFieldOf("msg_id").forGetter(c -> Optional.ofNullable(c.msgId))
        ).apply(instance, (attacker, msgId) -> new DeathCause(attacker.orElse(null), msgId.orElse(null))));

        public static final StreamCodec<FriendlyByteBuf, DeathCause> STREAM_CODEC = StreamCodec.composite(
                ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8), c -> Optional.ofNullable(c.attacker),
                ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8), c -> Optional.ofNullable(c.msgId),
                (attacker, msgId) -> new DeathCause(attacker.orElse(null), msgId.orElse(null)));
    }

    private final UUID id;
    private String speciesId;
    private String name;
    private boolean nameAutogenerated;
    private UUID parentA;
    private UUID parentB;
    private long birthWorldDay;
    private final long birthEpochMillis;
    private boolean deceased;
    private Long deathWorldDay;
    private Long deathEpochMillis;
    private UUID ownerId;
    private String ownerName;
    private String variantId;
    private LastSeen lastSeen;
    private DeathCause deathCause;

    public AnimalRecord(UUID id, String speciesId, String name, boolean nameAutogenerated,
                        UUID parentA, UUID parentB,
                        long birthWorldDay, long birthEpochMillis,
                        boolean deceased, Long deathWorldDay, Long deathEpochMillis,
                        UUID ownerId, String ownerName, String variantId,
                        LastSeen lastSeen, DeathCause deathCause) {
        this.id = id;
        this.speciesId = speciesId;
        this.name = name;
        this.nameAutogenerated = nameAutogenerated;
        this.parentA = parentA;
        this.parentB = parentB;
        this.birthWorldDay = birthWorldDay;
        this.birthEpochMillis = birthEpochMillis;
        this.deceased = deceased;
        this.deathWorldDay = deathWorldDay;
        this.deathEpochMillis = deathEpochMillis;
        this.ownerId = ownerId;
        this.ownerName = ownerName;
        this.variantId = variantId;
        this.lastSeen = lastSeen;
        this.deathCause = deathCause;
    }

    public UUID id() { return id; }
    public String speciesId() { return speciesId; }
    public String name() { return name; }
    public boolean nameAutogenerated() { return nameAutogenerated; }
    public UUID parentA() { return parentA; }
    public UUID parentB() { return parentB; }
    public long birthWorldDay() { return birthWorldDay; }
    public long birthEpochMillis() { return birthEpochMillis; }
    public boolean deceased() { return deceased; }
    public Long deathWorldDay() { return deathWorldDay; }
    public Long deathEpochMillis() { return deathEpochMillis; }
    public UUID ownerId() { return ownerId; }
    public String ownerName() { return ownerName; }
    public String variantId() { return variantId; }
    public LastSeen lastSeen() { return lastSeen; }
    public DeathCause deathCause() { return deathCause; }

    public void rename(String newName, boolean fromAutoGenerator) {
        this.name = newName;
        this.nameAutogenerated = fromAutoGenerator;
    }

    public void markDeceased(long worldDay, long epochMillis, DeathCause cause) {
        this.deceased = true;
        this.deathWorldDay = worldDay;
        this.deathEpochMillis = epochMillis;
        this.deathCause = cause;
    }

    public void updateLastSeen(double x, double y, double z, String dimension, long worldDay) {
        this.lastSeen = new LastSeen(x, y, z, dimension, worldDay);
    }

    public void setOwner(UUID ownerId, String ownerName) {
        this.ownerId = ownerId;
        this.ownerName = ownerName;
    }

    public void setSpeciesId(String speciesId) {
        this.speciesId = speciesId;
    }

    public void setParents(UUID parentA, UUID parentB) {
        this.parentA = parentA;
        this.parentB = parentB;
    }

    public void setBirthWorldDay(long birthWorldDay) {
        this.birthWorldDay = birthWorldDay;
    }

    public void setVariantId(String variantId) {
        this.variantId = variantId;
    }

    public static final Codec<AnimalRecord> CODEC = RecordCodecBuilder.create(instance -> instance.group(
            UUIDUtil.CODEC.fieldOf("id").forGetter(AnimalRecord::id),
            Codec.STRING.fieldOf("species").forGetter(AnimalRecord::speciesId),
            Codec.STRING.fieldOf("name").forGetter(AnimalRecord::name),
            Codec.BOOL.optionalFieldOf("name_auto", false).forGetter(AnimalRecord::nameAutogenerated),
            UUIDUtil.CODEC.optionalFieldOf("parent_a").forGetter(r -> Optional.ofNullable(r.parentA)),
            UUIDUtil.CODEC.optionalFieldOf("parent_b").forGetter(r -> Optional.ofNullable(r.parentB)),
            Codec.LONG.fieldOf("birth_world_day").forGetter(AnimalRecord::birthWorldDay),
            Codec.LONG.fieldOf("birth_epoch").forGetter(AnimalRecord::birthEpochMillis),
            Codec.BOOL.optionalFieldOf("deceased", false).forGetter(AnimalRecord::deceased),
            Codec.LONG.optionalFieldOf("death_world_day").forGetter(r -> Optional.ofNullable(r.deathWorldDay)),
            Codec.LONG.optionalFieldOf("death_epoch").forGetter(r -> Optional.ofNullable(r.deathEpochMillis)),
            UUIDUtil.CODEC.optionalFieldOf("owner").forGetter(r -> Optional.ofNullable(r.ownerId)),
            Codec.STRING.optionalFieldOf("owner_name").forGetter(r -> Optional.ofNullable(r.ownerName)),
            Codec.STRING.optionalFieldOf("variant_id").forGetter(r -> Optional.ofNullable(r.variantId)),
            LastSeen.CODEC.optionalFieldOf("last_seen").forGetter(r -> Optional.ofNullable(r.lastSeen)),
            DeathCause.CODEC.optionalFieldOf("death_cause").forGetter(r -> Optional.ofNullable(r.deathCause))
    ).apply(instance, (id, species, name, nameAuto, pa, pb, bd, be, dec, dwd, dem, owner, ownerName, variantId, lastSeen, deathCause) ->
            new AnimalRecord(id, species, name, nameAuto,
                    pa.orElse(null), pb.orElse(null),
                    bd, be,
                    dec, dwd.orElse(null), dem.orElse(null),
                    owner.orElse(null), ownerName.orElse(null), variantId.orElse(null),
                    lastSeen.orElse(null), deathCause.orElse(null))));

    public static final StreamCodec<FriendlyByteBuf, AnimalRecord> STREAM_CODEC = StreamCodec.of(
            AnimalRecord::encode,
            AnimalRecord::decode
    );

    private static void encode(FriendlyByteBuf buf, AnimalRecord record) {
        UUIDUtil.STREAM_CODEC.encode(buf, record.id);
        ByteBufCodecs.STRING_UTF8.encode(buf, record.speciesId);
        ByteBufCodecs.STRING_UTF8.encode(buf, record.name);
        ByteBufCodecs.BOOL.encode(buf, record.nameAutogenerated);
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.parentA));
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.parentB));
        ByteBufCodecs.LONG.encode(buf, record.birthWorldDay);
        ByteBufCodecs.LONG.encode(buf, record.birthEpochMillis);
        ByteBufCodecs.BOOL.encode(buf, record.deceased);
        ByteBufCodecs.optional(ByteBufCodecs.LONG).encode(buf, Optional.ofNullable(record.deathWorldDay));
        ByteBufCodecs.optional(ByteBufCodecs.LONG).encode(buf, Optional.ofNullable(record.deathEpochMillis));
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.ownerId));
        ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).encode(buf, Optional.ofNullable(record.ownerName));
        ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).encode(buf, Optional.ofNullable(record.variantId));
        ByteBufCodecs.optional(LastSeen.STREAM_CODEC).encode(buf, Optional.ofNullable(record.lastSeen));
        ByteBufCodecs.optional(DeathCause.STREAM_CODEC).encode(buf, Optional.ofNullable(record.deathCause));
    }

    private static AnimalRecord decode(FriendlyByteBuf buf) {
        UUID id = UUIDUtil.STREAM_CODEC.decode(buf);
        String species = ByteBufCodecs.STRING_UTF8.decode(buf);
        String name = ByteBufCodecs.STRING_UTF8.decode(buf);
        boolean nameAuto = ByteBufCodecs.BOOL.decode(buf);
        Optional<UUID> parentA = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        Optional<UUID> parentB = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        long birthWorldDay = ByteBufCodecs.LONG.decode(buf);
        long birthEpochMillis = ByteBufCodecs.LONG.decode(buf);
        boolean deceased = ByteBufCodecs.BOOL.decode(buf);
        Optional<Long> deathWorldDay = ByteBufCodecs.optional(ByteBufCodecs.LONG).decode(buf);
        Optional<Long> deathEpochMillis = ByteBufCodecs.optional(ByteBufCodecs.LONG).decode(buf);
        Optional<UUID> ownerId = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        Optional<String> ownerName = ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).decode(buf);
        Optional<String> variantId = ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).decode(buf);
        Optional<LastSeen> lastSeen = ByteBufCodecs.optional(LastSeen.STREAM_CODEC).decode(buf);
        Optional<DeathCause> deathCause = ByteBufCodecs.optional(DeathCause.STREAM_CODEC).decode(buf);
        return new AnimalRecord(
                id, species, name, nameAuto,
                parentA.orElse(null), parentB.orElse(null),
                birthWorldDay, birthEpochMillis,
                deceased, deathWorldDay.orElse(null), deathEpochMillis.orElse(null),
                ownerId.orElse(null), ownerName.orElse(null), variantId.orElse(null),
                lastSeen.orElse(null), deathCause.orElse(null)
        );
    }
}
