package com.egakh.familytree.data;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.UUIDUtil;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;

import java.util.Optional;
import java.util.UUID;

public final class AnimalRecord {
    private final UUID id;
    private String speciesId;
    private String name;
    private boolean nameAutogenerated;
    private UUID parentA;
    private UUID parentB;
    private long birthWorldDay;
    private final long birthEpochMillis;
    private boolean deceased;
    private Long deathWorldDay;
    private Long deathEpochMillis;
    private UUID ownerId;
    private String ownerName;
    private String variantId;

    public AnimalRecord(UUID id, String speciesId, String name, boolean nameAutogenerated,
                        UUID parentA, UUID parentB,
                        long birthWorldDay, long birthEpochMillis,
                        boolean deceased, Long deathWorldDay, Long deathEpochMillis,
                        UUID ownerId, String ownerName, String variantId) {
        this.id = id;
        this.speciesId = speciesId;
        this.name = name;
        this.nameAutogenerated = nameAutogenerated;
        this.parentA = parentA;
        this.parentB = parentB;
        this.birthWorldDay = birthWorldDay;
        this.birthEpochMillis = birthEpochMillis;
        this.deceased = deceased;
        this.deathWorldDay = deathWorldDay;
        this.deathEpochMillis = deathEpochMillis;
        this.ownerId = ownerId;
        this.ownerName = ownerName;
        this.variantId = variantId;
    }

    public UUID id() { return id; }
    public String speciesId() { return speciesId; }
    public String name() { return name; }
    public boolean nameAutogenerated() { return nameAutogenerated; }
    public UUID parentA() { return parentA; }
    public UUID parentB() { return parentB; }
    public long birthWorldDay() { return birthWorldDay; }
    public long birthEpochMillis() { return birthEpochMillis; }
    public boolean deceased() { return deceased; }
    public Long deathWorldDay() { return deathWorldDay; }
    public Long deathEpochMillis() { return deathEpochMillis; }
    public UUID ownerId() { return ownerId; }
    public String ownerName() { return ownerName; }
    public String variantId() { return variantId; }

    public void rename(String newName, boolean fromAutoGenerator) {
        this.name = newName;
        this.nameAutogenerated = fromAutoGenerator;
    }

    public void markDeceased(long worldDay, long epochMillis) {
        this.deceased = true;
        this.deathWorldDay = worldDay;
        this.deathEpochMillis = epochMillis;
    }

    public void setOwner(UUID ownerId, String ownerName) {
        this.ownerId = ownerId;
        this.ownerName = ownerName;
    }

    public void setSpeciesId(String speciesId) {
        this.speciesId = speciesId;
    }

    public void setParents(UUID parentA, UUID parentB) {
        this.parentA = parentA;
        this.parentB = parentB;
    }

    public void setBirthWorldDay(long birthWorldDay) {
        this.birthWorldDay = birthWorldDay;
    }

    public void setVariantId(String variantId) {
        this.variantId = variantId;
    }

    public static final Codec<AnimalRecord> CODEC = RecordCodecBuilder.create(instance -> instance.group(
            UUIDUtil.CODEC.fieldOf("id").forGetter(AnimalRecord::id),
            Codec.STRING.fieldOf("species").forGetter(AnimalRecord::speciesId),
            Codec.STRING.fieldOf("name").forGetter(AnimalRecord::name),
            Codec.BOOL.optionalFieldOf("name_auto", false).forGetter(AnimalRecord::nameAutogenerated),
            UUIDUtil.CODEC.optionalFieldOf("parent_a").forGetter(r -> Optional.ofNullable(r.parentA)),
            UUIDUtil.CODEC.optionalFieldOf("parent_b").forGetter(r -> Optional.ofNullable(r.parentB)),
            Codec.LONG.fieldOf("birth_world_day").forGetter(AnimalRecord::birthWorldDay),
            Codec.LONG.fieldOf("birth_epoch").forGetter(AnimalRecord::birthEpochMillis),
            Codec.BOOL.optionalFieldOf("deceased", false).forGetter(AnimalRecord::deceased),
            Codec.LONG.optionalFieldOf("death_world_day").forGetter(r -> Optional.ofNullable(r.deathWorldDay)),
            Codec.LONG.optionalFieldOf("death_epoch").forGetter(r -> Optional.ofNullable(r.deathEpochMillis)),
            UUIDUtil.CODEC.optionalFieldOf("owner").forGetter(r -> Optional.ofNullable(r.ownerId)),
            Codec.STRING.optionalFieldOf("owner_name").forGetter(r -> Optional.ofNullable(r.ownerName)),
            Codec.STRING.optionalFieldOf("variant_id").forGetter(r -> Optional.ofNullable(r.variantId))
    ).apply(instance, (id, species, name, nameAuto, pa, pb, bd, be, dec, dwd, dem, owner, ownerName, variantId) ->
            new AnimalRecord(id, species, name, nameAuto,
                    pa.orElse(null), pb.orElse(null),
                    bd, be,
                    dec, dwd.orElse(null), dem.orElse(null),
                    owner.orElse(null), ownerName.orElse(null), variantId.orElse(null))));

    public static final StreamCodec<FriendlyByteBuf, AnimalRecord> STREAM_CODEC = StreamCodec.of(
            AnimalRecord::encode,
            AnimalRecord::decode
    );

    private static void encode(FriendlyByteBuf buf, AnimalRecord record) {
        UUIDUtil.STREAM_CODEC.encode(buf, record.id);
        ByteBufCodecs.STRING_UTF8.encode(buf, record.speciesId);
        ByteBufCodecs.STRING_UTF8.encode(buf, record.name);
        ByteBufCodecs.BOOL.encode(buf, record.nameAutogenerated);
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.parentA));
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.parentB));
        ByteBufCodecs.LONG.encode(buf, record.birthWorldDay);
        ByteBufCodecs.LONG.encode(buf, record.birthEpochMillis);
        ByteBufCodecs.BOOL.encode(buf, record.deceased);
        ByteBufCodecs.optional(ByteBufCodecs.LONG).encode(buf, Optional.ofNullable(record.deathWorldDay));
        ByteBufCodecs.optional(ByteBufCodecs.LONG).encode(buf, Optional.ofNullable(record.deathEpochMillis));
        ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).encode(buf, Optional.ofNullable(record.ownerId));
        ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).encode(buf, Optional.ofNullable(record.ownerName));
        ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).encode(buf, Optional.ofNullable(record.variantId));
    }

    private static AnimalRecord decode(FriendlyByteBuf buf) {
        UUID id = UUIDUtil.STREAM_CODEC.decode(buf);
        String species = ByteBufCodecs.STRING_UTF8.decode(buf);
        String name = ByteBufCodecs.STRING_UTF8.decode(buf);
        boolean nameAuto = ByteBufCodecs.BOOL.decode(buf);
        Optional<UUID> parentA = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        Optional<UUID> parentB = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        long birthWorldDay = ByteBufCodecs.LONG.decode(buf);
        long birthEpochMillis = ByteBufCodecs.LONG.decode(buf);
        boolean deceased = ByteBufCodecs.BOOL.decode(buf);
        Optional<Long> deathWorldDay = ByteBufCodecs.optional(ByteBufCodecs.LONG).decode(buf);
        Optional<Long> deathEpochMillis = ByteBufCodecs.optional(ByteBufCodecs.LONG).decode(buf);
        Optional<UUID> ownerId = ByteBufCodecs.optional(UUIDUtil.STREAM_CODEC).decode(buf);
        Optional<String> ownerName = ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).decode(buf);
        Optional<String> variantId = ByteBufCodecs.optional(ByteBufCodecs.STRING_UTF8).decode(buf);
        return new AnimalRecord(
                id, species, name, nameAuto,
                parentA.orElse(null), parentB.orElse(null),
                birthWorldDay, birthEpochMillis,
                deceased, deathWorldDay.orElse(null), deathEpochMillis.orElse(null),
                ownerId.orElse(null), ownerName.orElse(null), variantId.orElse(null)
        );
    }
}
