package com.egakh.familytree.event;

import com.egakh.familytree.data.AnimalRecord;
import com.egakh.familytree.data.FamilyTreeState;
import com.egakh.familytree.naming.NameGenerator;
import com.egakh.familytree.util.PetFilter;
import com.egakh.familytree.util.TimeUtil;
import net.fabricmc.fabric.api.entity.event.v1.ServerLivingEntityEvents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.damagesource.DamageSource;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.OwnableEntity;
import net.minecraft.world.entity.animal.Animal;

import java.util.UUID;

public final class PetLifecycleListeners {

    private PetLifecycleListeners() {}

    public static void register() {
        ServerLivingEntityEvents.AFTER_DEATH.register(PetLifecycleListeners::onDeath);
    }

    public static void onBred(ServerLevel world, Animal parentA, Animal parentB, Animal child) {
        FamilyTreeState state = FamilyTreeState.get(world);

        ensureRecord(world, state, parentA);
        ensureRecord(world, state, parentB);

        UUID childId = child.getUUID();
        if (state.contains(childId)) return;

        String species = BuiltInRegistries.ENTITY_TYPE.getKey(child.getType()).toString();
        String existingName = nameOrNull(child);
        boolean autoNamed = existingName == null;
        String name = autoNamed ? NameGenerator.generate(childId) : existingName;

        UUID owner = ownerOf(child);
        if (owner == null) {
            UUID parentOwner = ownerOf(parentA);
            if (parentOwner == null) parentOwner = ownerOf(parentB);
            owner = parentOwner;
        }

        AnimalRecord rec = new AnimalRecord(
                childId,
                species,
                name,
                autoNamed,
                parentA.getUUID(),
                parentB.getUUID(),
                TimeUtil.currentWorldDay(world),
                TimeUtil.currentEpochMillis(),
                false, null, null,
                owner
        );
        state.put(rec);
    }

    public static void onCustomNameChanged(Entity entity, Component newName) {
        if (entity.level().isClientSide()) return;
        if (!(entity.level() instanceof ServerLevel serverLevel)) return;
        if (!PetFilter.isTameableSpecies(entity)) return;

        FamilyTreeState state = FamilyTreeState.get(serverLevel);
        UUID id = entity.getUUID();
        AnimalRecord existing = state.get(id);
        String displayName = newName == null ? null : newName.getString();
        if (displayName == null || displayName.isBlank()) return;

        if (existing != null) {
            state.update(id, r -> r.rename(displayName, false));
            return;
        }
        if (PetFilter.isTrackable(entity)) {
            ensureRecord(serverLevel, state, entity);
            state.update(id, r -> r.rename(displayName, false));
        }
    }

    private static void onDeath(LivingEntity entity, DamageSource source) {
        if (entity.level().isClientSide()) return;
        if (!(entity.level() instanceof ServerLevel world)) return;
        if (!PetFilter.isTameableSpecies(entity)) return;

        FamilyTreeState state = FamilyTreeState.get(world);
        UUID id = entity.getUUID();
        if (!state.contains(id)) return;
        state.update(id, r -> r.markDeceased(TimeUtil.currentWorldDay(world), TimeUtil.currentEpochMillis()));
    }

    public static void ensureRecord(ServerLevel world, FamilyTreeState state, Entity entity) {
        if (!PetFilter.isTrackable(entity)) return;
        UUID id = entity.getUUID();
        if (state.contains(id)) {
            UUID owner = ownerOf(entity);
            if (owner != null) state.update(id, r -> r.setOwner(owner));
            String currentName = nameOrNull(entity);
            if (currentName != null) {
                AnimalRecord r = state.get(id);
                if (r.nameAutogenerated() || !r.name().equals(currentName)) {
                    state.update(id, rec -> rec.rename(currentName, false));
                }
            }
            return;
        }

        String species = BuiltInRegistries.ENTITY_TYPE.getKey(entity.getType()).toString();
        String existingName = nameOrNull(entity);
        boolean autoNamed = existingName == null;
        String name = autoNamed ? NameGenerator.generate(id) : existingName;

        AnimalRecord rec = new AnimalRecord(
                id, species, name, autoNamed,
                null, null,
                TimeUtil.currentWorldDay(world),
                TimeUtil.currentEpochMillis(),
                false, null, null,
                ownerOf(entity)
        );
        state.put(rec);
    }

    private static String nameOrNull(Entity entity) {
        if (!entity.hasCustomName()) return null;
        Component name = entity.getCustomName();
        if (name == null) return null;
        String s = name.getString();
        return s.isBlank() ? null : s;
    }

    private static UUID ownerOf(Entity entity) {
        if (entity instanceof OwnableEntity ownable && ownable.getOwnerReference() != null) {
            return ownable.getOwnerReference().getUUID();
        }
        return null;
    }
}
